# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-20.04

trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

stages:
- stage: Build
  jobs:
  - job:
    displayName: "build"
    timeoutInMinutes: 60
    steps:
    - checkout: self
      clean: true
      submodules: recursive
      displayName: 'Checkout code'
    - script: |
        set -ex

        python3 setup.py bdist_wheel
        mkdir -p target/python-wheels/
        cp dist/swsssdk-2.0.1-py3-none-any.whl target/python-wheels/
      displayName: "Build"
    - script: |
        set -ex

        sudo py.test -v --force-flaky --junitxml=tr.xml
      displayName: "Test"
    - publish: $(System.DefaultWorkingDirectory)/target/python-wheels/
      artifact: sonic-py-swsssdk
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'tr.xml'
      condition: always()
