# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-20.04

trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

stages:
- stage: Build
  jobs:
  - job:
    displayName: "build"
    timeoutInMinutes: 60
    steps:
    - checkout: self
      clean: true
      submodules: recursive
      displayName: 'Checkout code'
    - script: |
        set -ex
        pip3 install setuptools
        python3 setup.py bdist_wheel
        sudo py.test -v --force-flaky --junitxml=tr.xml
        mkdir -p target/python-wheels/
    - publish: $(System.DefaultWorkingDirectory)
      artifact: swsssdk
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/tr.xml'
        testRunTitle: vstest
      condition: always()
